apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: default
spec:
  selector:
    app: webapi-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  namespace: default
  labels:
    app: webapi-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi-pod
  template:
    metadata:
      labels:
        app: webapi-pod
    spec:
      containers:
      - name: webapi-container
        image: mander77/devopstest:latest
        imagePullPolicy: IfNotPresent
        # securityContext:
        #   privileged: false
        #   readOnlyRootFilesystem: true
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   capabilities:
        #     drop:
        #     - ALL
        livenessProbe:
          httpGet:
            path: "/tags"
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: "/tags"
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5  
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi