apiVersion: v1
kind: Service
metadata:
  name: {{ include "conduit-deploy.fullname" . }}
  labels:
    {{- include "conduit-deploy.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: {{ .Values.api.service.protocol }}
      name: http
  selector:
    {{- include "conduit-deploy.selectorLabels" . | nindent 4 }}
